# Web Scraper Configuration

# Company to search for
company: "Paymaya"

# Search terms for different criteria
criteria:
  credibility:
    - "Review"
    - "Rating"
    - "Feedback"
  
  compliance:
    - "DTI"
    - "BIR"
    - "SEC"
  
  referential:
    - "Partners"
    - "Clients"

# Search settings
search_settings:
  num_results: 1  # Number of results to fetch per term
  min_delay: 1     # Minimum delay between requests (seconds)
  max_delay: 3     # Maximum delay between requests (seconds)
  timeout: 15      # Request timeout in seconds
